version: "3.7"

services:
  manager:
    user: root
    build:
      context: ..
      dockerfile: docker_init/dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 192.168.1.106:29092
      REDIS_HOST: 192.168.1.106
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
