version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    user: root
    image: "bitnami/kafka:2.8.1"
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://192.168.1.106:29092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    volumes:
      - "./kafka-data:/bitnami"
